### ISSUE TITLE
Roborock S7 ERR getState | {"code":"timeout"}

### ISSUE THREAD

**Issue by vordenken** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#496] opened 2022-05-30 16:36 UTC
I've used this plugin for over a year now without any problems but recently my homekit automations stopped working. I can't find the reason for this. One thing that's new is the error: "ERR getState | {"code":"timeout"}" appearing in the homebridge logs. 
I can control and use my vacuum in homekit without a problem. Only the automations are broken.

If you need any more information let me know :) Thanks!

**Comment by grmelacz** [comment] 2022-08-21 15:41
I'm getting the same error every couple of hours. The automations mostly work but I need to restart the Homebridge process every like 10-20 days or so once they stop to get them working again.

Probably duplicate of #459, #367, #243.

**Comment by afharo** [comment] 2022-08-27 08:33
There is a really hard-to-replicate bug in the underlying connection logic that is unable to recover the connection in some specific models of routers. 

I've been tweaking the `miio` library here and there a few times, and sometimes I improve it for some but not totally solve it for others. I'm planning to re-write the `miio` connectivity module entirely (I inherited a long time ago and I think it can be done better). Hopefully, it'll fix these kind of issues once and for all.

**Comment by afharo** [comment] 2022-08-31 23:01
@vordenken, can you join the discussion at #444? I'm trying to get to the bottom of this.

**Comment by afharo** [comment] 2023-01-25 22:48
I'll close this issue in favour of #444. Feel free to reopen it if you think that they are not related.

**Closed by afharo** 2023-01-25 22:48 UTC
